### ISSUE TITLE
Angular is not defined

### ISSUE THREAD

**Issue by debasreedash** [mattlewis92/angular-bootstrap-calendar#104]
Hi,

We are experiencing the same issue as the this issue:

https://github.com/mattlewis92/angular-bootstrap-calendar/issues/89#issuecomment-108512642

I noticed that it was fixed by changing links. Could you explain which links were changed?

Thanks,

Debbie

**Comment by debasreedash** [comment]
here is our error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module portfolioReporting due to:
Error: [$injector:modulerr] Failed to instantiate module mwl.calendar due to:
Error: [$injector:nomod] Module 'mwl.calendar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
	12:28 PM
Yao, Dennis	https://github.com/mattlewis92/angular-bootstrap-calendar
	12:33 PM
Dash, Debasree	https://github.com/rcalvogar/proyectoIntegrador
	12:40 PM
Le, Huu	Uncaught Error: [$injector:modulerr] Failed to instantiat...Uncaught Error: [$injector:modulerr] Failed to instantiate module portfolioReporting due to:
Error: [$injector:modulerr] Failed to instantiate module mwl.calendar due to:
Error: [$injector:nomod] Module 'mwl.calendar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.1/$injector/nomod?p0=mwl.calendar
    at REGEX_STRING_REGEXP (http://localhost:4001/scripts/vendor-18f086cf.js:68:12)
    at http://localhost:4001/scripts/vendor-18f086cf.js:1949:17
    at ensure (http://localhost:4001/scripts/vendor-18f086cf.js:1873:38)
    at module (http://localhost:4001/scripts/vendor-18f086cf.js:1947:14)
    at http://localhost:4001/scripts/vendor-18f086cf.js:4355:22
    at forEach (http://localhost:4001/scripts/vendor-18f086cf.js:336:20)
    at loadModules (http://localhost:4001/scripts/vendor-18f086cf.js:4339:5)
    at http://localhost:4001/scripts/vendor-18f086cf.js:4356:40
    at forEach (http://localhost:4001/scripts/vendor-18f086cf.js:336:20)
    at loadModules (http://localhost:4001/scripts/vendor-18f086cf.js:4339:5)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=mwl.calendar&p1=Err…20(http%3A%2F%2Flocalhost%3A4001%2Fscripts%2Fvendor-18f086cf.js%3A4339%3A5)
    at REGEX_STRING_REGEXP (http://localhost:4001/scripts/vendor-18f086cf.js:68:12)
    at http://localhost:4001/scripts/vendor-18f086cf.js:4378:15
    at forEach (http://localhost:4001/scripts/vendor-18f086cf.js:336:20)
    at loadModules (http://localhost:4001/scripts/vendor-18f086cf.js:4339:5)
    at http://localhost:4001/scripts/vendor-18f086cf.js:4356:40
    at forEach (http://localhost:4001/scripts/vendor-18f086cf.js:336:20)
    at loadModules (http://localhost:4001/scripts/vendor-18f086cf.js:4339:5)
    at createInjector (http://localhost:4001/scripts/vendor-18f086cf.js:4265:11)
    at doBootstrap (http://localhost:4001/scripts/vendor-18f086cf.js:1621:20)
    at bootstrap (http://localhost:4001/scripts/vendor-18f086cf.js:1642:12)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=portfolioReporting&…0(http%3A%2F%2Flocalhost%3A4001%2Fscripts%2Fvendor-18f086cf.js%3A1642%3A12)REGEX_STRING_REGEXP @ vendor-18f086cf.js:68(anonymous function) @ vendor-18f086cf.js:4378forEach @ vendor-18f086cf.js:336loadModules @ vendor-18f086cf.js:4339createInjector @ vendor-18f086cf.js:4265doBootstrap @ vendor-18f086cf.js:1621bootstrap @ vendor-18f086cf.js:1642angularInit @ vendor-18f086cf.js:1536(anonymous function) @ vendor-18f086cf.js:28289trigger @ vendor-18f086cf.js:2989eventHandler @ vendor-18f086cf.js:3264
	1:00 PM

**Comment by mattlewis92** [comment]
Looks like you're not including your scripts in the right order. It needs to be 
1. angular
2. the calendar dist file / any other vendor code
3. your code

**Comment by mattlewis92** [comment]
Closing to keep open issues tidy. Let me know if you're still having problems and I'll do what I can to help :)
