### ISSUE TITLE
Deprecation warning from moment

### ISSUE THREAD

**Issue by appnupNet** [mattlewis92/angular-bootstrap-calendar#551]
### Bug description / Feature request:

Got this warning when tried to use the directive.
I guess it is not that critical but I thought it worth mentioning it here for future releases
Thanks

Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 03, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:23:668)
    at fb (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:146:129)
    at qb (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:212:413)
    at pb (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:212:274)
    at ob (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:210:274)
    at rb (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:217:160)
    at sb (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:217:194)
    at a (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js:6:202)
    at Object.c.$onInit (http://localhost:3000/components/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min.js:7:30005)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:9295:34

### Versions

Angular: 
1.5.8
Calendar library: 
0.28.1
Browser name and version: 
Chrome 56.0.2924.87

**Comment by burtek** [comment]
To be honest I'm not getting that error in this example...

**Comment by mattlewis92** [comment]
I think the issue is because of the date formats you're providing to the calendar as this warning doesn't show up in the demo which uses the same moment version. If you can make a plunker that reproduces your problem I can try and dig in more  😄
