### ISSUE TITLE
implemented from plunker but still getting this error

### ISSUE THREAD

**Issue by rnkpareek** [mattlewis92/angular-bootstrap-calendar#657]
GET http://localhost:4200/config.js net::ERR_ABORTED
(index):16 GET http://localhost:4200/config.js net::ERR_ABORTED
zone.js:32 Uncaught Error: Zone already loaded.
    at eval (zone.js:32)
    at eval (zone.js:646)
    at FUNCTION (zone.js:9)
    at Object.eval (zone.js:12)
    at eval (zone.js:3026)
    at Object.../../../../zone.js/dist/zone.js (polyfills.bundle.js:605)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (polyfills.ts:1)
    at Object.../../../../../src/polyfills.ts (polyfills.bundle.js:7)
    at __webpack_require__ (inline.bundle.js:55)
(anonymous) @ zone.js:32
(anonymous) @ zone.js:646
FUNCTION @ zone.js:9
(anonymous) @ zone.js:12
(anonymous) @ zone.js:3026
../../../../zone.js/dist/zone.js @ polyfills.bundle.js:605
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ polyfills.ts:1
../../../../../src/polyfills.ts @ polyfills.bundle.js:7
__webpack_require__ @ inline.bundle.js:55
1 @ polyfills.bundle.js:612
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ polyfills.bundle.js:1
zone.js:2933 GET http://localhost:4200/app 404 (Not Found)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
W @ system.src.js:1043
(anonymous) @ system.src.js:1779
ZoneAwarePromise @ zone.js:890
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:2803
(anonymous) @ system.src.js:3381
(anonymous) @ system.src.js:3713
(anonymous) @ system.src.js:4105
(anonymous) @ system.src.js:4570
(anonymous) @ system.src.js:4839
(anonymous) @ system.src.js:408
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
(anonymous) @ system.src.js:4797
import @ system.src.js:830
(anonymous) @ system.src.js:1802
(anonymous) @ (index):18
zone.js:392 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:4200/app
	Error: XHR error (404 Not Found) loading http://localhost:4200/app
	    at o (https://unpkg.com/systemjs@0.19.47/dist/system.js:4:17461)
	    at XMLHttpRequest.W.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (https://unpkg.com/systemjs@0.19.47/dist/system.js:4:18049)
	    at XMLHttpRequest.wrapFn (https://unpkg.com/zone.js@0.8.18/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:425:31)
	    at Zone.runTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (https://unpkg.com/zone.js@0.8.18/dist/zone.js:499:34)
	    at invokeTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (https://unpkg.com/zone.js@0.8.18/dist/zone.js:1566:17)

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by burtek** [comment]
@rnkpareek angular-calendar project for angular 2+ is [here](https://github.com/mattlewis92/angular-calendar). This is AngularJS project.
